# Generated by Django 4.1.2 on 2022-11-12 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0.0)),
                ('image', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=32)),
                ('title', models.TextField(max_length=255)),
                ('reviewScore', models.FloatField(default=None, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
