# Generated by Django 4.0.6 on 2022-08-03 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0001_create_wishlist_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product_id')},
        ),
    ]
